const airports = [
  { code: "LHR", name: "London Heathrow", city: "London, United Kingdom", language: "en" },
  { code: "DEL", name: "Indira Gandhi International", city: "New Delhi, India", language: "hi" },
  { code: "JFK", name: "New York John F. Kennedy", city: "New York, USA", language: "en" },
  { code: "DXB", name: "Dubai International", city: "Dubai, UAE", language: "ar" },
  { code: "MAN", name: "Manchester Airport", city: "Manchester, United Kingdom", language: "en" },
  { code: "SIN", name: "Singapore Changi", city: "Singapore", language: "en" },
  { code: "CDG", name: "Paris Charles de Gaulle", city: "Paris, France", language: "fr" },
  { code: "HND", name: "Tokyo Haneda", city: "Tokyo, Japan", language: "ja" },
  { code: "SYD", name: "Sydney Kingsford Smith", city: "Sydney, Australia", language: "en" },
  { code: "YYZ", name: "Toronto Pearson", city: "Toronto, Canada", language: "en" },
  { code: "SFO", name: "San Francisco International", city: "San Francisco, USA", language: "en" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt, Germany", language: "de" },
  { code: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam, Netherlands", language: "nl" },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles, USA", language: "en" },
  { code: "ICN", name: "Seoul Incheon", city: "Seoul, South Korea", language: "ko" },
  { code: "BOM", name: "Mumbai Chhatrapati Shivaji", city: "Mumbai, India", language: "hi" },
  { code: "BCN", name: "Barcelona El Prat", city: "Barcelona, Spain", language: "es" },
  { code: "GRU", name: "São Paulo Guarulhos", city: "São Paulo, Brazil", language: "pt" },
  { code: "JNB", name: "Johannesburg O.R. Tambo", city: "Johannesburg, South Africa", language: "en" },
  { code: "CPT", name: "Cape Town International", city: "Cape Town, South Africa", language: "en" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul, Türkiye", language: "tr" },
  { code: "MEL", name: "Melbourne Tullamarine", city: "Melbourne, Australia", language: "en" },
  { code: "SZX", name: "Shenzhen Bao'an", city: "Shenzhen, China", language: "zh" },
];

export default airports;
