const airports = [
  { code: "LHR", name: "London Heathrow", city: "London, United Kingdom", language: "en", lat: 51.4706, lon: -0.4619 },
  { code: "DEL", name: "Indira Gandhi International", city: "New Delhi, India", language: "hi", lat: 28.5562, lon: 77.1000 },
  { code: "JFK", name: "New York John F. Kennedy", city: "New York, USA", language: "en", lat: 40.6413, lon: -73.7781 },
  { code: "DXB", name: "Dubai International", city: "Dubai, UAE", language: "ar", lat: 25.2532, lon: 55.3657 },
  { code: "MAN", name: "Manchester Airport", city: "Manchester, United Kingdom", language: "en", lat: 53.365, lon: -2.272 },
  { code: "SIN", name: "Singapore Changi", city: "Singapore", language: "en", lat: 1.3644, lon: 103.9915 },
  { code: "CDG", name: "Paris Charles de Gaulle", city: "Paris, France", language: "fr", lat: 49.0097, lon: 2.5479 },
  { code: "HND", name: "Tokyo Haneda", city: "Tokyo, Japan", language: "ja", lat: 35.5494, lon: 139.7798 },
  { code: "SYD", name: "Sydney Kingsford Smith", city: "Sydney, Australia", language: "en", lat: -33.9399, lon: 151.1753 },
  { code: "YYZ", name: "Toronto Pearson", city: "Toronto, Canada", language: "en", lat: 43.6777, lon: -79.6248 },
  { code: "SFO", name: "San Francisco International", city: "San Francisco, USA", language: "en", lat: 37.6213, lon: -122.379 },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt, Germany", language: "de", lat: 50.0379, lon: 8.5622 },
  { code: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam, Netherlands", language: "nl", lat: 52.3105, lon: 4.7683 },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles, USA", language: "en", lat: 33.9416, lon: -118.4085 },
  { code: "ICN", name: "Seoul Incheon", city: "Seoul, South Korea", language: "ko", lat: 37.4691, lon: 126.4505 },
  { code: "BOM", name: "Mumbai Chhatrapati Shivaji", city: "Mumbai, India", language: "hi", lat: 19.0896, lon: 72.8656 },
  { code: "BCN", name: "Barcelona El Prat", city: "Barcelona, Spain", language: "es", lat: 41.2974, lon: 2.0833 },
  { code: "GRU", name: "São Paulo Guarulhos", city: "São Paulo, Brazil", language: "pt", lat: -23.4356, lon: -46.4731 },
  { code: "JNB", name: "Johannesburg O.R. Tambo", city: "Johannesburg, South Africa", language: "en", lat: -26.1337, lon: 28.2420 },
  { code: "CPT", name: "Cape Town International", city: "Cape Town, South Africa", language: "en", lat: -33.9690, lon: 18.5972 },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul, Türkiye", language: "tr", lat: 41.2753, lon: 28.7519 },
  { code: "MEL", name: "Melbourne Tullamarine", city: "Melbourne, Australia", language: "en", lat: -37.6690, lon: 144.8410 },
  { code: "SZX", name: "Shenzhen Bao'an", city: "Shenzhen, China", language: "zh", lat: 22.6393, lon: 113.8107 },
];

export default airports;
